name: 11ty build
on: [push]
permissions:
  contents: write
jobs:
  build-deploy:
    name: Build Website and Deploy on Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm install
      - name: Build Website
        run: npx @11ty/eleventy --pathprefix=resume-serverless
      - name: Build Tailwind CSS
        run: |
          mkdir dist/assets/css
          npx postcss tailwind.css > dist/assets/css/style.css
      - name: Deploy on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}